name: Hello World DNB Training Workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the User
        run: echo "Hello World!"
